### ISSUE TITLE
NullPointerException while executing run tasks

### ISSUE THREAD

**Issue by mdtanrikulu** [ibcn-cloudlet/dianne#9]
I got following error when I execute`./gradlew run.all` [Any of them; all , core etc.]

```
2017-08-02 13:36:44.210:INFO:oejs.Server:jetty-8.1.14.v20131031
2017-08-02 13:36:44.283:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
[INFO] Started Jetty 8.1.14.v20131031 at port(s) HTTP:8080 on context path /
[DEBUG] Ignoring Servlet Service ServiceReference{org.apache.felix.http.base.internal.handler.HttpServicePlugin@229d10bd}, alias is missing or empty
[INFO] Detected extended HttpService. Filters enabled.
[DEBUG] Ignoring Servlet Service ServiceReference{org.apache.felix.http.whiteboard.internal.manager.HttpWhiteboardWebConsolePlugin@63a65a25}, alias is missing or empty
[INFO] Http service whiteboard started
Exception in thread "Thread-25" java.lang.NullPointerException
	at be.iminds.aiolos.monitor.node.NodeMonitorImpl.update(NodeMonitorImpl.java:159)
	at be.iminds.aiolos.monitor.node.NodeMonitorImpl.access$2(NodeMonitorImpl.java:118)
	at be.iminds.aiolos.monitor.node.NodeMonitorImpl$MonitorThread.run(NodeMonitorImpl.java:261)
	at java.lang.Thread.run(Thread.java:745)

Welcome to Apache Felix Gogo

g! 
> Building 85% > :tools:run.core
```

And it hangs at 85%.

**Comment by tverbele** [comment]
The NPE comes from an optional bundle that gathers system monitoring information by reading from the Linux /proc/ filesystem. If this is not present it fails with that exception, but should not keep DIANNE from working.

Also when using the run target in gradle, the build will pause when it launched DIANNE, and will only reach 100% when the process is stopped. So at this moment DIANNE is actually up and running and you should see the user interface when pointing your browser to http://localhost:8080/dianne

**Comment by mdtanrikulu** [comment]
Well, I've this instead;

<img width="578" alt="screen shot 2017-08-02 at 15 34 16" src="https://user-images.githubusercontent.com/2774845/28876041-14bf9642-7798-11e7-947a-f8205be29300.png">

**Comment by tverbele** [comment]
When the build process hangs, can you press enter, type `lb` and hit enter again? You are running `run.all` right?

**Comment by mdtanrikulu** [comment]
Yes, this is `run.all` on the picture and `run.core` also same.
<img width="521" alt="screen shot 2017-08-02 at 21 41 23" src="https://user-images.githubusercontent.com/2774845/28891604-5f234020-77cb-11e7-9af2-533dc4a062eb.png">

**Comment by tverbele** [comment]
Hmm, could you also provide the output of `src:list` and `log debug`?

**Comment by mdtanrikulu** [comment]
This is for `log debug`;

```
2017.08.07 11:37:11 INFO - Bundle: org.eclipse.concierge - ServiceReference{aQute.launcher.Launcher@3c77d488} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.nn - BundleEvent STARTED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.nn.module - ServiceReference{Component: be.iminds.iot.dianne.nn.module.composite.CompositeModuleFactory (31)} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.jsonrpc - ServiceReference{Component: be.iminds.iot.dianne.jsonrpc.DianneJSONRPCServlet (22)} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.jsonrpc - ServiceReference{Component: be.iminds.iot.dianne.jsonrpc.DianneJSONRPCCLI (20)} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.jsonrpc - ServiceReference{Component: be.iminds.iot.dianne.jsonrpc.DianneRequestHandler (23)} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.command - ServiceReference{Component: be.iminds.iot.dianne.command.DiannePlatformCommands (19)} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.command - ServiceReference{Component: be.iminds.iot.dianne.command.DianneBenchmarkCommands (17)} - ServiceEvent REGISTERED
2017.08.07 11:37:11 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneRunner (15)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneDeployer (9)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneLearner (11)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@5143878e} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@77273ebf} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@d82863f} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.nn.module - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneBuilder (7)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@6661f096} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.nn.module - ServiceReference{Component: be.iminds.iot.dianne.nn.module.factory.DianneModuleFactory (32)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.nn.util - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.nn.util - ServiceReference{Component: be.iminds.iot.dianne.nn.util.strategy.StrategyFactoryImpl (30)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.api - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.tensor.util - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.tensor - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.tensor - ServiceReference{Component: be.iminds.iot.dianne.tensor.serializer.TensorSerializer (29)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.tensor - ServiceReference{Component: be.iminds.iot.dianne.tensor.NativeTensorLoader (28)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.dashboard - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.dashboard - ServiceReference{Component: be.iminds.iot.dianne.dashboard.DianneDownload (27)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.dashboard - ServiceReference{Component: be.iminds.iot.dianne.dashboard.DianneDashboard (26)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.coordinator - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.command - ServiceReference{Component: be.iminds.iot.dianne.command.DianneCoordinatorCommands (18)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@2b537423} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.jsonrpc - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.jsonrpc - ServiceReference{Component: be.iminds.iot.dianne.jsonrpc.DianneSSEServlet (24)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.command - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneSaver (16)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneRedirect (14)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneLoader (12)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.builder - ServiceReference{Component: be.iminds.iot.dianne.builder.DianneData (8)} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@654f6530} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.rl.experience - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.iot.dianne.dataset - BundleEvent STARTED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@7c65b4d8} - ServiceEvent REGISTERED
2017.08.07 11:37:10 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@15e91e82} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.iot.dianne.repository - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ServiceProxy@25ab8270} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.iot.dianne.nn.platform - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.platformmanager - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.platformmanager - ServiceReference{be.iminds.aiolos.platform.command.PlatformCommands@3b531510} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.platformmanager - ServiceReference{be.iminds.aiolos.platform.PlatformManagerImpl@6ac1a5d6} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.proxymanager - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.command.ProxyCommands@3781bb02} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.proxymanager - ServiceReference{be.iminds.aiolos.proxy.ProxyManagerImpl@4ec00780} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.topologymanager - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.topologymanager - ServiceReference{be.iminds.aiolos.topology.command.TopologyManagerCommands@6d9870dd} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.topologymanager - ServiceReference{be.iminds.aiolos.topology.TopologyManagerImpl@242b836} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.topologymanager - ServiceReference{be.iminds.aiolos.topology.TopologyManagerImpl@242b836} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.topologymanager - ServiceReference{be.iminds.aiolos.topology.TopologyManagerImpl@242b836} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.nodemonitor - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.nodemonitor - ServiceReference{be.iminds.aiolos.monitor.node.NodeMonitorImpl@a1087ad} - ServiceEvent REGISTERED
2017.08.07 11:37:09 WARNING - Bundle: be.iminds.aiolos.nodemonitor - Error reading cpu monitor information: /proc/stat (No such file or directory)
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.remoteserviceadmin - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.remoteserviceadmin - ServiceReference{be.iminds.aiolos.rsa.command.RSACommands@30737446} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: be.iminds.aiolos.remoteserviceadmin - ServiceReference{be.iminds.aiolos.rsa.ROSGiServiceAdmin@4f80542f} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: de.javakaffee.kryo-serializers - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: com.esotericsoftware.kryo - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: org.objenesis - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: com.google.gson - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: kxml - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.scr - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.scr - ServiceReference{org.apache.felix.scr.impl.config.ScrManagedServiceServiceFactory@7e4189cf} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.scr - ServiceReference{org.apache.felix.scr.impl.ScrGogoCommand@50f11042} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.scr - ServiceReference{org.apache.felix.scr.impl.runtime.ServiceComponentRuntimeImpl@5e52d81e} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.scr - ServiceReference{org.apache.felix.scr.impl.config.ConfigurationSupport@752856d6} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.metatype - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.metatype - ServiceReference{org.apache.felix.metatype.internal.MetaTypeServiceImpl@355ce81c} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.log - BundleEvent STARTED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.log - ServiceReference{org.apache.felix.log.LogReaderServiceFactory@7d5a64d} - ServiceEvent REGISTERED
2017.08.07 11:37:09 INFO - Bundle: org.apache.felix.log - ServiceReference{org.apache.felix.log.LogServiceFactory@5f7ec5f5} - ServiceEvent REGISTERED
```

But I'm getting `CommandNotFoundException: Command not found: src:list` error for `src:list`

**Comment by tverbele** [comment]
The log seems fine... could you try pointing your browser directly to `http://localhost:8080/dianne/ui/builder/builder.html`

**Comment by mdtanrikulu** [comment]
Here it is. Can it be used?

<img width="1419" alt="screen shot 2017-08-09 at 15 49 46" src="https://user-images.githubusercontent.com/2774845/29124884-74c0d0f6-7d1a-11e7-9b1f-d3da1a1d1924.png">

**Comment by tverbele** [comment]
Looking at the logs everything seems up and running. I think only the shorthand /dianne URL redirect didn't work. Which system/browser are you running on?

**Comment by mdtanrikulu** [comment]
macOS/Unix - Chrome.

**Comment by tverbele** [comment]
The redirect problem should be fixed in the latest master branch. For know you can just use the full url as stated, shouldn't make a difference.

**Comment by mdtanrikulu** [comment]
Thank you so much. I've just confirmed it and it's working well. 
Just a little suggestion, if the `/` root  router is free to use, it could be nice to redirect it to the dianne dashboard too. It's a bit complicated as it is now.

**Comment by tverbele** [comment]
Thanks for the suggestion, we'll look into it

**Comment by tverbele** [comment]
I have added a redirect from the root / , should be working now if you checkout and build the latest master

**Comment by khalidpandit** [comment]
we are facing issue... it hangs at 85% and i m not able to redirect to localhost.

How shall I proceed

**Comment by tverbele** [comment]
Try the complete url `http://localhost:8080/dianne/ui/builder/builder.html` . Which version are you running? Redirecting the localhost root can only work on latest master.

**Comment by khalidpandit** [comment]
![d](https://user-images.githubusercontent.com/13897759/37951052-9b82dab0-31b8-11e8-81c4-f98110087571.png)

**Comment by tverbele** [comment]
did you change the .bndrun configurations somehow? Normally you should also have the following bundles active:

```
   28|Active     |Dianne Platform (0.7.0.201803261842)
   29|Active     |Dianne NN Repository (0.7.0.201803261842)
   30|Active     |Dianne Datasets (0.7.0.201803262029)
   31|Active     |Dianne Experience Pools (0.7.0.201803262029)
   32|Active     |Dianne Builder UI (0.7.0.201803262030)
   33|Active     |Dianne GoGo Shell CLI (0.7.0.201803261842)
   34|Active     |Dianne JSON RPC (0.7.0.201803261842)
   35|Active     |Dianne Coordinator (0.7.0.201803261842)
   36|Active     |Dianne Dashboard UI (0.7.0.201803261842)
   37|Active     |Dianne Tensor Library (0.7.0.201803230845)
   38|Resolved   |Dianne Tensor Library - native implementation (0.7.0.201803230845)
   39|Active     |Dianne Tensor utils (0.7.0.201803262029)
   40|Active     |Dianne API (0.7.0.201803261842)
   41|Active     |Dianne Utilities (0.7.0.201803261842)
   42|Active     |Dianne NN modules (0.7.0.201803262030)
   43|Active     |Dianne Neural Network bundle (0.7.0.201803261842)
   44|Active     |Dianne RNN Modules (0.7.0.201803262030)
   45|Active     |Dianne RNN Datasets (0.7.0.201803262030)
```

**Comment by eliasdc** [comment]
It looks like you are only running the `runtime.jar` instead of the `standalone.jar` or `all.jar`. The runtime only jar does not include the builder UI.

Try the following:
```bash
./gradlew export.all run.all
```
